sudo: false
language: cpp
compiler: gcc
script: make nibbler && make activity04 && make activity05 && make codewrite && make circlemath && make factorial && make review-session1 && make system-of-particles && make review-session-2
